apiVersion: v1
kind: Pod
metadata:
  name: psql-client
  namespace: hiveforge-controller
spec:
  containers:
  - name: psql-client
    image: postgres:16
    command: ["sleep", "3600"]
    env:
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: "hiveforge-database-secret"
            key: postgres-username
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "hiveforge-database-secret"
            key: postgres-password
      - name: DB_NAME
        value: "hiveforge-controller"
      - name: DB_HOST
        value: "hiveforge-cluster.hiveforge-database.svc.cluster.local"
      - name: DB_PORT
        value: "5432"
