apiVersion: v1
kind: Pod
metadata:
  name: psql-client
  namespace: hiveforge-controller
spec:
  containers:
  - name: psql-client
    image: postgres:16
    command: ["sleep", "3600"]
    env:
    - name: PGPOOL_USERNAME
      valueFrom:
        secretKeyRef:
          name: hiveforge-database-secret
          key: pgpool-admin-username
    - name: PGPOOL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: hiveforge-database-secret
          key: pgpool-admin-password
    - name: PGPOOL_DATABASE
      value: "hiveforge-controller"
    - name: PGPOOL_HOST
      value: "hiveforge-database-postgresql-ha-pgpool.hiveforge-database.svc.cluster.local"
    - name: PGPOOL_PORT
      value: "5432"
