apiVersion: batch/v1
kind: Job
metadata:
  name: hiveforge-db-setup
spec:
  template:
    metadata:
      name: db-setup
    spec:
      restartPolicy: Never
      volumes:
        - name: postgres-ca-cert
          configMap:
            name: postgres-ca-cert
      containers:
      - name: db-setup
        image: "{{.Values.migration.image.registry }}/{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}"
        command: ["/bin/sh", "-c", "./migrate.sh && sleep 3600"]
        volumeMounts:
          - name: postgres-ca-cert
            mountPath: /etc/ssl/postgres
            readOnly: true
        env:
          - name: POSTGRES_CACERTFILE
            value: /etc/ssl/postgres/ca.crt
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.tunables.database.secretName }}"
                key: postgres-username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.tunables.database.secretName }}"
                key: postgres-password
          - name: DB_NAME
            value: "{{ .Values.tunables.database.name }}"
          - name: DB_HOST
            value: "{{ .Values.tunables.database.clusterName }}-pooler.{{ .Values.tunables.database.namespace }}.svc.cluster.local"
          - name: DB_PORT
            value: "{{ .Values.tunables.network.pgbouncerPort }}"
