apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: default
spec:
  containers:
  - name: curl-container
    image: curlimages/curl:8.8.0
    command: [ "sh", "-c", "curl http://hiveforge-controller-service.hiveforge-controller.svc.cluster.local:80/api/v1/activejobs" ]
  restartPolicy: Never
